POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "What's new with NestJS",
  "postType": "post",
  "slug": "new-with-nestjs-3422231233",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2025-05-03T13:40:39.076Z",
  "tagsIds": [
    1,4
  ],
  "metaOptions": {
    "meta_value": "{\"key\":\"value\"}"
  },
  "authorId": 3
}